### ISSUE TITLE
Question: SIP with Quectel EC25E/RM520N

### ISSUE THREAD

**Issue by ChibangLW** [fgsect/scat#79]
Not sure if this is the correct place to ask questions. My goal ist to see SIP Messages and as a bonus RTP streams in Wireshark.

I collected logs (.qmdl and qmdl2 files) with QLog. When using scat with `scat -t qc -d log.qmdl -F test.pcap` I do see SIP Messages as raw UDP payload in Wireshark (screenshot). From the latest release I would have hoped to see them actually show up as SIP protocol in Wireshark. Is this a missunderstanding or wrong configuration on my end? The same happens if I directly log with scat from the diag serial interface.
![wireshark-scat](https://github.com/fgsect/scat/assets/22293464/9d21df9d-58e2-489f-b8c3-150e99c95fc1)

**Comment by peremen** [comment]
Because SIP messages through the separate DIAG log packet are not encapsulated in any transport layer protocol, I added a fictional UDP and IP header and sent the packet through UDP port 47290. Decode UDP port 47290 as IP, then you will see everything.

Q: Why I can't see the real P-CSCF and UE IP address?
A: It is not available along with the DIAG item carrying SIP message. Also I wanted to avoid parsing NAS messages.
