### ISSUE TITLE
directly fetch diag info using on-device script

### ISSUE THREAD

**Issue by NeutrinoLiu** [fgsect/scat#89]
i noticed that in the previous discussion, pixel series are pretty hard to expose their diag port to the host. 
So I want running some RRC analysis script in an on-device manner (using turmux). But the problem is there is no such serial or usb devices available for me to connect to within an android device. 
I am wondering if there is one way we could directly fetch those lower layer packets (or logs). One thing i have found pretty close to what i am looking for is [diag_revealer](https://github.com/mobile-insight/mobileinsight-mobile/blob/master/diag_revealer/qcom/jni/diag_revealer.c)   by mobileinsight apps. But i am rookie in android development. Will it be a good idea to combine diag_revealer with scat?

**Comment by peremen** [comment]
It is hard to maintain the device companion app:
* Needs to support and test on each baseband type/OEM due to customizations and different SoC kernel baseline version
* Qualcomm has at least 9 methods to open `/dev/diag` device node to get the DIAG data (also see [this](https://telegra.ph/ru-fieldtest-modemcaps-faq-03-26))
* Recent Samsung Exynos modem locks on-device DM access when the device is rooted (according to some other sources), although not applied on Pixel devices
* For all other baseband I don't have enough resource to look into it

[QCSuper](https://github.com/P1sec/QCSuper/) uses companion app based design though, but I am not going to use that design due to maintenance problem (see #29).

SCAT itself is not designed with any post-processing other than GSMTAP wrapping and printing packet information in mind.
